I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 43, in script
    m "Привет"
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 43, in script
    m "Привет"
  File "/Users/keda/Documents/renpy-8.3.2-sdk/renpy/ast.py", line 2573, in execute
    Say.execute(self)
  File "/Users/keda/Documents/renpy-8.3.2-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/keda/Documents/renpy-8.3.2-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'm' is not defined.

macOS-10.15.7-x86_64-i386-64bit x86_64
Ren'Py 8.3.2.24090902
The SunFlower 1.0
Wed Nov  6 20:54:54 2024
